language: java

jdk:
    - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)


addons:
  sonarcloud:
    organization: "rkonovalov-github" # the key of the org you chose at step #3

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - sonar-scanner